rpisubsonic:
  build: .
  ports:
    - 8080:8080
  environment:
    VIRTUAL_HOST: subsonic
    VIRTUAL_PORT: 8080
  volumes:
    - ./volume-var_subsonic:/var/subsonic
    - /home/fozz/Store/jukebox:/music:ro
  command: /subsonic-boot
