- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  tasks:
    - apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
      sudo: true
    - apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main" state=present
      sudo: true
    - apt: pkg={{ item }} state=present
      with_items:
      - elasticsearch
      - default-jdk
      sudo: true
    - name: "Set ElasticSearch to start on system startup"
      shell: update-rc.d elasticsearch defaults 95 10
      sudo: true
    - name: "Restart ElasticSearch"
      shell: service elasticsearch restart
      sudo: true