# # Subsonic provisioning for Raspberry Pi
# 
# Run the contents of this to install ansible before hand
#
# `sudo apt-get update ; sudo apt-get -y install python-pip python-dev ; sudo pip install ansible ; sudo mkdir /etc/ansible ; sudo bash -c "echo [audio] >> /etc/ansible/hosts" ; sudo bash -c "echo 127.0.0.1 >> /etc/ansible/hosts" ; ssh -o StrictHostKeyChecking=no git@github.com`

- hosts: localhost
  vars:
    http_port: 8080
    build_root: ~/build_root
  tasks:

    # Build
    - apt_repository: repo="ppa:kirillshkrogalev/ffmpeg-next" update_cache=true
      sudo: true
    - apt: pkg={{ item }} state=present
      with_items:
      - maven
      - openjdk-7-jdk
      - git
      - tomcat6
      - ffmpeg
      sudo: true
    - user: name=root groups=audio append=yes
      sudo: true
    - file: path={{ build_root }} state=directory
    - git: repo=https://github.com/EugeneKay/subsonic.git version=release dest={{ build_root }}/subsonic
    - shell: mvn package
      args:
        chdir: "{{ build_root }}/subsonic"
        creates: "{{ build_root }}/subsonic/subsonic-main/target/subsonic.war"

    # Install
    - service: name=tomcat6 state=stopped
      sudo: true
    - file: path={{ item }} state=absent
      with_items:
        - /var/lib/tomcat6/webapps/subsonic 
        - /var/lib/tomcat6/work
        - /var/subsonic
      sudo: true
    - file: path={{ item }} state=directory owner=tomcat6 group=tomcat6
      with_items:
        - /var/subsonic 
        - /var/lib/tomcat6/work
      sudo: true
    - copy: src="{{ build_root }}/subsonic/subsonic-main/target/subsonic.war" dest=/var/lib/tomcat6/webapps/
      sudo: true
    # - service: name=tomcat6 state=restarted
    #   sudo: true
